-- Radiant Alpha shop — orders schema.
--
-- Run once by hand in Hostinger's phpMyAdmin (hPanel → Databases → phpMyAdmin).
-- Hostinger shared hosting has no migration runner, and this repo has no
-- automated DB tooling — this file is documentation of what was run, not
-- something any build step executes.
--
-- Two tables, not one status column and not a fully normalised history-only
-- design: `orders` holds current state for cheap admin-list queries, and
-- `order_status_history` is an append-only log of when each status was set,
-- which a single column can't answer. Every status write goes through one
-- shared PHP function (markOrderPaid() in public/_lib/orders.php, and the
-- admin status-change handler) that updates both together, so they cannot
-- drift apart.

CREATE TABLE IF NOT EXISTS orders (
  id                       INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,

  -- Generated by us as 'RA-' . bin2hex(random_bytes(8)) before ever calling
  -- Paystack — 64 bits of entropy, since this doubles as half of the
  -- customer tracking page's auth check (reference + email).
  reference                VARCHAR(40)  NOT NULL UNIQUE,

  -- Every product/variant/price field below is a SNAPSHOT at purchase time,
  -- not a foreign key into the catalogue. A later price change on the site
  -- must never rewrite what a past order says it cost.
  product_id               VARCHAR(80)  NOT NULL,
  product_label            VARCHAR(160) NOT NULL,
  variant_ref              VARCHAR(80)  NOT NULL,
  variant_label            VARCHAR(80)  NOT NULL,
  amount_kobo              BIGINT UNSIGNED NOT NULL,
  currency                 CHAR(3)      NOT NULL DEFAULT 'NGN',

  customer_name            VARCHAR(120) NOT NULL,
  customer_email           VARCHAR(190) NOT NULL,
  customer_phone           VARCHAR(40)  NOT NULL,

  status                   ENUM('pending','paid','processing','shipped','delivered','failed')
                             NOT NULL DEFAULT 'pending',
  status_updated_at        DATETIME     NOT NULL,

  paystack_transaction_id  BIGINT UNSIGNED NULL,

  created_at               DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at               DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  INDEX idx_customer_email (customer_email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS order_status_history (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  order_id   INT UNSIGNED NOT NULL,
  status     ENUM('pending','paid','processing','shipped','delivered','failed') NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (order_id) REFERENCES orders(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
