<?php
declare(strict_types=1);

require_once __DIR__ . '/config.php';

const PAYSTACK_API_BASE = 'https://api.paystack.co';

/**
 * Low-level request wrapper. TLS verification and a timeout are never
 * optional here — a payment integration is the last place to silently skip
 * either. Returns Paystack's own decoded JSON shape (`status`, `message`,
 * `data`) on any successful HTTP round trip; on a transport failure it
 * fabricates a `status: false` shape so callers only ever need one check.
 */
function paystackRequest(string $method, string $path, ?array $body = null): array
{
    $config = appConfig();
    $ch = curl_init(PAYSTACK_API_BASE . $path);

    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_SSL_VERIFYPEER => true,
        CURLOPT_SSL_VERIFYHOST => 2,
        CURLOPT_TIMEOUT => 15,
        CURLOPT_CUSTOMREQUEST => $method,
        CURLOPT_HTTPHEADER => [
            'Authorization: Bearer ' . $config['paystack_secret_key'],
            'Content-Type: application/json',
        ],
    ]);
    if ($body !== null) {
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($body));
    }

    $response = curl_exec($ch);
    $errno = curl_errno($ch);
    $curlError = curl_error($ch);
    curl_close($ch);

    if ($errno !== 0 || $response === false) {
        error_log("paystackRequest($method $path): cURL error [$errno] $curlError");
        return ['status' => false, 'message' => 'Network error contacting Paystack'];
    }

    $decoded = json_decode($response, true);
    if (!is_array($decoded)) {
        error_log("paystackRequest($method $path): non-JSON response");
        return ['status' => false, 'message' => 'Invalid response from Paystack'];
    }

    return $decoded;
}

/**
 * Initialise a transaction. $amountKobo is already the naira price converted
 * to kobo by the caller — this function does not do currency math, only
 * calls the API. $reference must be generated by us before this call
 * (generateOrderReference() in orders.php), never accepted from the client.
 */
function paystackInitialize(string $email, int $amountKobo, string $reference, string $callbackUrl): array
{
    return paystackRequest('POST', '/transaction/initialize', [
        'email' => $email,
        'amount' => $amountKobo,
        'reference' => $reference,
        'callback_url' => $callbackUrl,
        'currency' => 'NGN',
    ]);
}

/**
 * Server-side verification of a transaction — the only source either
 * order-callback.php or an operator should ever trust for "did this actually
 * get paid." Never inferred from a redirect query string alone.
 */
function paystackVerify(string $reference): array
{
    return paystackRequest('GET', '/transaction/verify/' . rawurlencode($reference));
}
